# Generated by Django 4.0.4 on 2022-04-19 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='year',
            field=models.CharField(max_length=4),
        ),
    ]
