# Generated by Django 3.0 on 2022-04-19 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jewelry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('metal', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=250)),
                ('color', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
            ],
        ),
    ]
